[tox]
envlist = py312, py313, py314

[testenv]
description = Run the test suite under {basepython}
extras = dev
commands =
    pytest {posargs:tests}

[gh]
python =
    3.12 = py312
    3.13 = py313
    3.14 = py314
